### ISSUE TITLE
implicit declaration of PMU_set_voltage

### ISSUE THREAD

**Issue by plat-zhaw** [GreenWaves-Technologies/keyword_spotting#1]
Hi there,

I just compiled and run this application on the gpauino with the sensor board. It works fine, nice work.

During compilation one warning is shown:
```
main_with_mfcc.c: In function 'kws_ds_cnn':
main_with_mfcc.c:208:9: warning: implicit declaration of function 'PMU_set_voltage' [-Wimplicit-function-declaration]
         PMU_set_voltage(voltage, 0);
         ^~~~~~~~~~~~~~~
```
It seems that this function cannot be found. As I said, the application works. I Just thought you might want to know.

**Comment by Pafrak** [comment]
Hello,
 yes, this is an old API, I will update it. Thanks for the report.
